apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: bk
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31001
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bk
      tier: frontend
  template:
    metadata:
      labels:
        app: bk
        tier: frontend
    spec:
      containers:
        - name: bk
          image: beank99/bk-frontend
          ports:
            - containerPort: 3000
