apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: contest73
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest73-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest73
      tier: frontend
  template:
    metadata:
      labels:
        app: contest73
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: beank99/contest73-frontend
          ports:
            - containerPort: 3000
